# Generated by Django 5.0.14 on 2026-07-27 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatJabatanAkademik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jabatan', models.CharField(choices=[('asisten_ahli', 'Asisten Ahli'), ('lektor', 'Lektor'), ('lektor_kepala', 'Lektor Kepala'), ('guru_besar', 'Guru Besar')], max_length=20)),
                ('tmt', models.DateField(help_text='Tanggal Mulai Tugas / tanggal berlaku jabatan akademik ini.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan_akademik', to='pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Riwayat Jabatan Akademik',
                'verbose_name_plural': 'Riwayat Jabatan Akademik',
                'ordering': ['pegawai', 'tmt'],
            },
        ),
    ]
