# Generated by Django 5.0.14 on 2026-07-27 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPendukung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alamat', models.TextField(blank=True, help_text='Alamat domisili saat ini.')),
                ('kontak_darurat_nama', models.CharField(blank=True, help_text='Nama kontak darurat (next-of-kin).', max_length=100)),
                ('kontak_darurat_hubungan', models.CharField(blank=True, help_text='Contoh: Suami, Istri, Orang tua, Saudara kandung.', max_length=50)),
                ('kontak_darurat_no_hp', models.CharField(blank=True, max_length=20)),
                ('email_kedua', models.EmailField(blank=True, help_text='Email alternatif di luar email institusi.', max_length=254)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_pendukung', to='pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Data Pendukung',
                'verbose_name_plural': 'Data Pendukung',
            },
        ),
    ]
