# Generated by Django 5.0.14 on 2026-07-27 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisasi', '0001_initial'),
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatJabatanStruktural',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmt', models.DateField(help_text='Tanggal Mulai Tugas / tanggal mulai menjabat.')),
                ('selesai', models.DateField(blank=True, help_text='Tanggal berakhir menjabat. Kosongkan jika masih menjabat.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_jabatan_struktural', to='organisasi.jabatanstrukturalmaster')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan_struktural', to='pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Riwayat Jabatan Struktural',
                'verbose_name_plural': 'Riwayat Jabatan Struktural',
                'ordering': ['pegawai', 'tmt'],
            },
        ),
    ]
