# Generated by Django 5.0.14 on 2026-07-27 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nip_nidn', models.CharField(help_text='NIP untuk tendik, NIDN untuk dosen.', max_length=30, unique=True)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('jenis_pegawai', models.CharField(choices=[('dosen', 'Dosen'), ('tendik', 'Tenaga Kependidikan')], max_length=10)),
                ('unit_kerja', models.CharField(help_text='Contoh: Fakultas Teknik, Biro Administrasi Umum.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Akun login yang terhubung dengan data pegawai ini.', on_delete=django.db.models.deletion.PROTECT, related_name='pegawai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
