# Generated by Django 5.0.14 on 2026-07-27 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKepangkatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('golongan', models.CharField(choices=[('II/a', 'II/a'), ('II/b', 'II/b'), ('II/c', 'II/c'), ('II/d', 'II/d'), ('III/a', 'III/a'), ('III/b', 'III/b'), ('III/c', 'III/c'), ('III/d', 'III/d'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('IV/c', 'IV/c'), ('IV/d', 'IV/d'), ('IV/e', 'IV/e')], max_length=6)),
                ('tmt', models.DateField(help_text='Tanggal Mulai Tugas / tanggal berlaku golongan ini.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kepangkatan', to='pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Riwayat Kepangkatan',
                'verbose_name_plural': 'Riwayat Kepangkatan',
                'ordering': ['pegawai', 'tmt'],
            },
        ),
    ]
