# Generated by Django 5.0.14 on 2026-07-27 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanStrukturalMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=100, unique=True)),
                ('level', models.PositiveSmallIntegerField(help_text='Urutan hierarki, contoh: 1=Rektor, 2=Dekan, 3=Kaprodi.')),
                ('aktif', models.BooleanField(default=True, help_text='Nonaktifkan jika jabatan ini sudah tidak berlaku, jangan dihapus.')),
            ],
            options={
                'verbose_name': 'Jabatan Struktural (Master)',
                'ordering': ['level', 'nama_jabatan'],
            },
        ),
    ]
