# Generated by Django 5.0.14 on 2026-07-27 19:00

from django.db import migrations


def seed_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    for kode, _ in [
        ("admin", "Admin"),
        ("staff_sdm", "Staff SDM"),
        ("dosen", "Dosen"),
        ("tendik", "Tenaga Kependidikan"),
    ]:
        Role.objects.get_or_create(nama_role=kode)

def unseed_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(nama_role__in=["admin", "staff_sdm", "dosen", "tendik"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_roles, reverse_code=unseed_roles),
    ]
