# Generated by Django 5.0.14 on 2026-07-27 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatStudi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenjang', models.CharField(choices=[('S1', 'Sarjana (S1)'), ('S2', 'Magister (S2)'), ('S3', 'Doktor (S3)')], max_length=2)),
                ('institusi', models.CharField(help_text='Nama perguruan tinggi tempat menempuh studi.', max_length=150)),
                ('gelar', models.CharField(help_text='Contoh: S.Kom, M.T, Dr.', max_length=50)),
                ('tahun_lulus', models.DateField(help_text='Tanggal/tahun kelulusan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_studi', to='pegawai.pegawai')),
            ],
            options={
                'verbose_name': 'Riwayat Studi',
                'verbose_name_plural': 'Riwayat Studi',
                'ordering': ['pegawai', 'tahun_lulus'],
            },
        ),
    ]
